version: "3"

services:
  mysql:
    image: mysql:5.7
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
      - "--max_allowed_packet=512M"
    container_name: ${SITE_NAME}_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    env_file: .env
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
  wordpress:
    env_file: .env
    args:
      USER_NAME: ${USER_NAME}
    build: .
    container_name: ${SITE_NAME}_wp
    ports:
      - "${WORDPRESS_LOCAL_PORT}:80"
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    user: "1000:1000"
    volumes:
      - ./public:/var/www/html
  wordmove:
    env_file: .env
    args:
      USER_NAME: ${USER_NAME}
    build: wordmove
    container_name: ${SITE_NAME}_wordmove
    tty: true
    depends_on:
      - wordpress
    user: "1000:1000"
    volumes:
      - ./public:/html
      - ./wordmove:/home/${USER_NAME}/wordmove
      - ~/.ssh:/home/${USER_NAME}/.ssh
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${SITE_NAME}_phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    env_file: .env
    ports:
      - "${PMA_LOCAL_PORT}:80"

volumes:
  db_data:
    name: ${SITE_NAME}_data
    driver: local

